name: GitHub CI
on: push

jobs:
  

  buildLibosx2:
    name: Build Release Lib2
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: msbuild /p:Configuration="AppStore" /p:Platform="iPhone" /p:IpaPackageDir=bin/iPhone/AppStore /p:BuildIpa=true "ExtLibs/Xamarin/Xamarin.iOS/Xamarin.iOS.csproj"
