name: GitHub CI
on: push

jobs:
  

  buildLibosx2:
    name: Build Release Lib2
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: msbuild -v:m -restore /p:Configuration="Ad-Hoc" /p:Platform="iPhoneSimulator" /p:IpaPackageDir=bin/iPhoneSimulator/Ad-Hoc /p:BuildIpa=true "ExtLibs/Xamarin/Xamarin.iOS/Xamarin.iOS.csproj"


  buildLibosx3:
    name: Build Release Lib3
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: msbuild -v:m -restore /p:Configuration="Debug" /p:Platform="iPhone" /p:IpaPackageDir=bin/iPhone/Debug /p:BuildIpa=true "ExtLibs/Xamarin/Xamarin.iOS/Xamarin.iOS.csproj"
