name: GitHub CI
on: push

jobs:
  

  buildLibosx2:
    name: Build Release Lib2
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: msbuild -v:m -restore /p:Configuration="Ad-Hoc" /p:Platform="iPhone" /p:IpaPackageDir=bin/iPhone/Ad-Hoc /p:BuildIpa=false "ExtLibs/Xamarin/Xamarin.iOS/Xamarin.iOS.csproj"
